/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_shadowyy_jni_TestJNI */

#ifndef _Included_com_shadowyy_jni_TestJNI
#define _Included_com_shadowyy_jni_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shadowyy_jni_TestJNI
 * Method:    hello
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_shadowyy_jni_TestJNI_hello
        (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif